import React from "react"
import PageHeader from "Components/pageheader"
import Wrapper from "Components/contentWrapper"
import Button from "Components/button"
import Icon from "Components/icon"
import {apiKeyData} from "./../mock-data"
import DataTable from "Components/table/custom-table"
import Moment from "moment"
import Dialog from "Components/dialog"

class Api extends React.Component {

  constructor() {
    super()

    this.state = {
      generateKey: false,
      deleteKey: false
    }

    this.apiTableHeaders = [
      {title: "Name", icon: ""},
      {title: "API Key", icon: ""}, 
      {title: "Time", icon: ""},
      {title: "Generated by", icon: ""},
      {title: "", icon: ""}
    ]
    
    this.generateApiKey = this.generateApiKey.bind(this)
    this.mountApiKeyModal = this.mountApiKeyModal.bind(this)
    this.unMountApiKeyModal = this.unMountApiKeyModal.bind(this)
    this.deleteApiKey = this.deleteApiKey.bind(this)
  }

  deleteApiKey() {
    console.log("delete api key")
    this.setState({ deleteKey: false })
  }

  generateApiKey() {
    this.setState({ generateKey: false })
    console.log("Generate api key")
  }

  mountApiKeyModal(action) {
    if(action === "generate") {
      this.setState({ generateKey: true })
    } else {
      this.setState({ deleteKey: true })
    }
  }

  unMountApiKeyModal(action) {
    if(action === "generate") {
      this.setState({ generateKey: false })
    } else {
      this.setState({ deleteKey: false })
    }
  }

  render() {
    const {generateKey, deleteKey} = this.state
    return (
      <div id="apiContainer">
        <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%'}}>
          <PageHeader pageName="APIs" />
          <span>
            <Button primary onClick={() => this.mountApiKeyModal("generate")}>
              Generate Api
              <span style={{marginLeft: '10px', verticalAlign: '-webkit-baseline-middle'}}>
                <Icon name="channelTick" /> 
              </span>
            </Button>
          </span>
        </span>
        <Wrapper>
          <div className="body">
            <DataTable
              headings={this.apiTableHeaders}
              loadingData={false}
              className="logs"
            >
            {
              apiKeyData.length &&
              apiKeyData.map((item, i) => {
                return (
                  <tr key={i}>
                    <td>{item.name}</td>
                    <td>{item.api_key}</td>
                    <td>{Moment(item.created_at).format("DD/MM/YYYY")}</td>
                    <td>{item.generated_by}</td>
                    <td style={{cursor: 'pointer'}} onClick={() => this.mountApiKeyModal("delete")}>
                      <Icon name="delete" />
                    </td>
                  </tr>
                )
              })
            }
            </DataTable>
            <div style={{marginTop: '60px'}}>
              <Button danger>API Documentation</Button>
            </div>
          </div>
        </Wrapper>
        {generateKey && (
          <Dialog
            title="Generate New API Key"
            subtitle="New API Key created"
            inputBox={true}
            onClick={() => this.unMountApiKeyModal("generate")}
            actions={[
              <Button onClick={() => this.generateApiKey()} primary>
                Generate
              </Button>,
              <Button onClick={() => this.unMountApiKeyModal("generate")} secondary>
                Cancel
              </Button>
            ]}
          />
        )}
        {deleteKey && (
          <Dialog
            title={`Do you want to delete "API Key ${1}"`}
            onClick={() => this.unMountApiKeyModal("delete")}
            actions={[
              <Button onClick={() => this.deleteApiKey()} primary>
                Yes
              </Button>,
              <Button onClick={() => this.unMountApiKeyModal("delete")} secondary>
                No
              </Button>
            ]}
          />
        )}
      </div>
    )
  }
}

export default Api